import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { NextAuthProvider } from "@/components/providers/authProviders";

export const metadata: Metadata = {
  title: "Task Management App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NextAuthProvider>
      <html lang="en">
        <body>
          <div className='bg-gray-50'>
            <nav className="bg-white shadow-md border-b border-gray-200">
              <div className="container mx-auto px-4">
                <div className="flex items-center justify-between h-16">
                  <div className="flex items-center">
                    <h1 className="text-xl font-bold text-gray-800">
                      Tasks Management
                    </h1>
                  </div>
                  <div className="flex space-x-1">
                    <Link href="/dashboard">
                      <h1 className="px-4 py-2 rounded-md text-sm font-medium transition-colors duration-200 bg-blue-600 text-white">
                        DashBoard
                      </h1>
                    </Link>
                  </div>
                </div>
              </div>
            </nav>
          </div>
          {children}
        </body >
      </html >
    </NextAuthProvider>
  );
}
